name: jappeos_greeter
description: "The login UI for JappeOS."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.20.2
  shadcn_flutter:
    git:
      url: https://github.com/JappeOS/shadcn_flutter.git
      ref: master
  jappeos_services:
    git:
      url: https://github.com/JappeOS/jappeos_services.git
      ref: dev
  widget_and_text_animator: ^1.1.5
  provider: ^6.1.5+1
  crypt: ^4.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true